### ISSUE TITLE
Support using "blocking" and "async_impl" features at the same time

### ISSUE THREAD

**Issue by pnehrer** [gklijs/schema_registry_converter#39]
**Is your feature request related to a problem? Please describe.**
I have a cargo workspace with several projects that use the schema_registry_converter. Some of them are tools that use the `blocking` implementation (i.e., no need for `async_impl`), but some are server apps, which need to use `async_impl`.

Because the workspace builds dependencies configured with the union of all features listed across all projects, I end up not being able to use `async_impl` anywhere as long as at least one of the projects uses `blocking`.

**Describe the solution you'd like**
I would like to be able to select both `async_impl` as well as `blocking` features without one disabling the other.

**Describe alternatives you've considered**
For now, I get around it by including the `kafka_test` feature, which ends up allowing `blocking` alongside `async_impl`, but this seems like a hack.

**Additional context**
Is there a specific reason why `blocking` automatically precludes `async_impl`?

https://github.com/gklijs/schema_registry_converter/blob/master/src/lib.rs#L24

I realize one must have at least one of them enabled, but the mechanism that you describe in an example (i.e., `default-features = false, features = ["blocking"]`) seems to provide that.

Thank you!

**Comment by gklijs** [comment]
Hi, thanks for creating the issue.
I imagined the library to be often used with the rdkafka crate, and changed the default to async because they kind of did as well.
The separation of the async and blocking I stole from reqwest.
I didn't imagine users want both and the current way of not loading the async when blocking seemed nice. But I think I could change the check for the async module from `not blocking` to `futures`. Making it easier to use both.

**Comment by gklijs** [comment]
I'm awaiting the build. The async is now dependent on the `futures` feature, that is set by default. So for you case you should be able to remove the `kafka_test` feature, and you still have them both. To use only async nothing is changed, since excluding default features will already exclude async.

**Comment by pnehrer** [comment]
That's great, thank you!
